scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level4`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
    game.gameOver(false)
})
let Kevin = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    .........f.f............
    ..........f.............
    .......5555555..........
    ......555fff555.........
    ......bbf111fbb.........
    ......fbf1f1fbf.........
    ......bbf111fbb.........
    ......555fff555.........
    ......855555558.........
    .....58855555885........
    .....58888ff8885........
    ....55888f8888855.......
    ....5f.88f8ff8.f5.......
    .......588ff85..........
    ......ff.....ff.........
    `, SpriteKind.Player)
let Bobs_Bear = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ....e...e...............
    ...e5eee5e..............
    ....efefe...............
    .....efe................
    ....eeeee...............
    .....eee................
    .....e.e................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
controller.moveSprite(Kevin)
tiles.setCurrentTilemap(tilemap`level2`)
tiles.placeOnRandomTile(Kevin, assets.tile`myTile0`)
tiles.placeOnRandomTile(Bobs_Bear, assets.tile`myTile0`)
scene.cameraFollowSprite(Kevin)
Bobs_Bear.follow(Kevin)
